"""Add explanation field to MatchResult

Revision ID: 34a01fbe1b69
Revises: bab17c3da3fc
Create Date: 2025-06-19 19:54:15.223272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a01fbe1b69'
down_revision = 'bab17c3da3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    # ### end Alembic commands ###
