"""Add MatchResult table

Revision ID: bab17c3da3fc
Revises: 
Create Date: 2025-06-19 19:28:55.458244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab17c3da3fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('matched_email', sa.String(length=120), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('top_emotions', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_result')
    # ### end Alembic commands ###
